// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package looprpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AssetsClientClient is the client API for AssetsClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssetsClientClient interface {
	SwapOut(ctx context.Context, in *SwapOutRequest, opts ...grpc.CallOption) (*SwapOutResponse, error)
	ListAssetSwaps(ctx context.Context, in *ListAssetSwapsRequest, opts ...grpc.CallOption) (*ListAssetSwapsResponse, error)
	ClientListAvailableAssets(ctx context.Context, in *ClientListAvailableAssetsRequest, opts ...grpc.CallOption) (*ClientListAvailableAssetsResponse, error)
	ClientGetAssetSwapOutQuote(ctx context.Context, in *ClientGetAssetSwapOutQuoteRequest, opts ...grpc.CallOption) (*ClientGetAssetSwapOutQuoteResponse, error)
	BeginSwapIn(ctx context.Context, in *BeginSwapInRequest, opts ...grpc.CallOption) (*BeginSwapInResponse, error)
	QuoteSwapIn(ctx context.Context, in *QuoteSwapInRequest, opts ...grpc.CallOption) (*QuoteSwapInResponse, error)
	ExecuteSwapIn(ctx context.Context, in *ExecuteSwapInRequest, opts ...grpc.CallOption) (*ExecuteSwapInResponse, error)
}

type assetsClientClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetsClientClient(cc grpc.ClientConnInterface) AssetsClientClient {
	return &assetsClientClient{cc}
}

func (c *assetsClientClient) SwapOut(ctx context.Context, in *SwapOutRequest, opts ...grpc.CallOption) (*SwapOutResponse, error) {
	out := new(SwapOutResponse)
	err := c.cc.Invoke(ctx, "/looprpc.AssetsClient/SwapOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsClientClient) ListAssetSwaps(ctx context.Context, in *ListAssetSwapsRequest, opts ...grpc.CallOption) (*ListAssetSwapsResponse, error) {
	out := new(ListAssetSwapsResponse)
	err := c.cc.Invoke(ctx, "/looprpc.AssetsClient/ListAssetSwaps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsClientClient) ClientListAvailableAssets(ctx context.Context, in *ClientListAvailableAssetsRequest, opts ...grpc.CallOption) (*ClientListAvailableAssetsResponse, error) {
	out := new(ClientListAvailableAssetsResponse)
	err := c.cc.Invoke(ctx, "/looprpc.AssetsClient/ClientListAvailableAssets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsClientClient) ClientGetAssetSwapOutQuote(ctx context.Context, in *ClientGetAssetSwapOutQuoteRequest, opts ...grpc.CallOption) (*ClientGetAssetSwapOutQuoteResponse, error) {
	out := new(ClientGetAssetSwapOutQuoteResponse)
	err := c.cc.Invoke(ctx, "/looprpc.AssetsClient/ClientGetAssetSwapOutQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsClientClient) BeginSwapIn(ctx context.Context, in *BeginSwapInRequest, opts ...grpc.CallOption) (*BeginSwapInResponse, error) {
	out := new(BeginSwapInResponse)
	err := c.cc.Invoke(ctx, "/looprpc.AssetsClient/BeginSwapIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsClientClient) QuoteSwapIn(ctx context.Context, in *QuoteSwapInRequest, opts ...grpc.CallOption) (*QuoteSwapInResponse, error) {
	out := new(QuoteSwapInResponse)
	err := c.cc.Invoke(ctx, "/looprpc.AssetsClient/QuoteSwapIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsClientClient) ExecuteSwapIn(ctx context.Context, in *ExecuteSwapInRequest, opts ...grpc.CallOption) (*ExecuteSwapInResponse, error) {
	out := new(ExecuteSwapInResponse)
	err := c.cc.Invoke(ctx, "/looprpc.AssetsClient/ExecuteSwapIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetsClientServer is the server API for AssetsClient service.
// All implementations must embed UnimplementedAssetsClientServer
// for forward compatibility
type AssetsClientServer interface {
	SwapOut(context.Context, *SwapOutRequest) (*SwapOutResponse, error)
	ListAssetSwaps(context.Context, *ListAssetSwapsRequest) (*ListAssetSwapsResponse, error)
	ClientListAvailableAssets(context.Context, *ClientListAvailableAssetsRequest) (*ClientListAvailableAssetsResponse, error)
	ClientGetAssetSwapOutQuote(context.Context, *ClientGetAssetSwapOutQuoteRequest) (*ClientGetAssetSwapOutQuoteResponse, error)
	BeginSwapIn(context.Context, *BeginSwapInRequest) (*BeginSwapInResponse, error)
	QuoteSwapIn(context.Context, *QuoteSwapInRequest) (*QuoteSwapInResponse, error)
	ExecuteSwapIn(context.Context, *ExecuteSwapInRequest) (*ExecuteSwapInResponse, error)
	mustEmbedUnimplementedAssetsClientServer()
}

// UnimplementedAssetsClientServer must be embedded to have forward compatible implementations.
type UnimplementedAssetsClientServer struct {
}

func (UnimplementedAssetsClientServer) SwapOut(context.Context, *SwapOutRequest) (*SwapOutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwapOut not implemented")
}
func (UnimplementedAssetsClientServer) ListAssetSwaps(context.Context, *ListAssetSwapsRequest) (*ListAssetSwapsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAssetSwaps not implemented")
}
func (UnimplementedAssetsClientServer) ClientListAvailableAssets(context.Context, *ClientListAvailableAssetsRequest) (*ClientListAvailableAssetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientListAvailableAssets not implemented")
}
func (UnimplementedAssetsClientServer) ClientGetAssetSwapOutQuote(context.Context, *ClientGetAssetSwapOutQuoteRequest) (*ClientGetAssetSwapOutQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientGetAssetSwapOutQuote not implemented")
}
func (UnimplementedAssetsClientServer) BeginSwapIn(context.Context, *BeginSwapInRequest) (*BeginSwapInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeginSwapIn not implemented")
}
func (UnimplementedAssetsClientServer) QuoteSwapIn(context.Context, *QuoteSwapInRequest) (*QuoteSwapInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuoteSwapIn not implemented")
}
func (UnimplementedAssetsClientServer) ExecuteSwapIn(context.Context, *ExecuteSwapInRequest) (*ExecuteSwapInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteSwapIn not implemented")
}
func (UnimplementedAssetsClientServer) mustEmbedUnimplementedAssetsClientServer() {}

// UnsafeAssetsClientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetsClientServer will
// result in compilation errors.
type UnsafeAssetsClientServer interface {
	mustEmbedUnimplementedAssetsClientServer()
}

func RegisterAssetsClientServer(s grpc.ServiceRegistrar, srv AssetsClientServer) {
	s.RegisterService(&AssetsClient_ServiceDesc, srv)
}

func _AssetsClient_SwapOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwapOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsClientServer).SwapOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/looprpc.AssetsClient/SwapOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsClientServer).SwapOut(ctx, req.(*SwapOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsClient_ListAssetSwaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAssetSwapsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsClientServer).ListAssetSwaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/looprpc.AssetsClient/ListAssetSwaps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsClientServer).ListAssetSwaps(ctx, req.(*ListAssetSwapsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsClient_ClientListAvailableAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientListAvailableAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsClientServer).ClientListAvailableAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/looprpc.AssetsClient/ClientListAvailableAssets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsClientServer).ClientListAvailableAssets(ctx, req.(*ClientListAvailableAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsClient_ClientGetAssetSwapOutQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientGetAssetSwapOutQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsClientServer).ClientGetAssetSwapOutQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/looprpc.AssetsClient/ClientGetAssetSwapOutQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsClientServer).ClientGetAssetSwapOutQuote(ctx, req.(*ClientGetAssetSwapOutQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsClient_BeginSwapIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginSwapInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsClientServer).BeginSwapIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/looprpc.AssetsClient/BeginSwapIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsClientServer).BeginSwapIn(ctx, req.(*BeginSwapInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsClient_QuoteSwapIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteSwapInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsClientServer).QuoteSwapIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/looprpc.AssetsClient/QuoteSwapIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsClientServer).QuoteSwapIn(ctx, req.(*QuoteSwapInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsClient_ExecuteSwapIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteSwapInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsClientServer).ExecuteSwapIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/looprpc.AssetsClient/ExecuteSwapIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsClientServer).ExecuteSwapIn(ctx, req.(*ExecuteSwapInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetsClient_ServiceDesc is the grpc.ServiceDesc for AssetsClient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetsClient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "looprpc.AssetsClient",
	HandlerType: (*AssetsClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SwapOut",
			Handler:    _AssetsClient_SwapOut_Handler,
		},
		{
			MethodName: "ListAssetSwaps",
			Handler:    _AssetsClient_ListAssetSwaps_Handler,
		},
		{
			MethodName: "ClientListAvailableAssets",
			Handler:    _AssetsClient_ClientListAvailableAssets_Handler,
		},
		{
			MethodName: "ClientGetAssetSwapOutQuote",
			Handler:    _AssetsClient_ClientGetAssetSwapOutQuote_Handler,
		},
		{
			MethodName: "BeginSwapIn",
			Handler:    _AssetsClient_BeginSwapIn_Handler,
		},
		{
			MethodName: "QuoteSwapIn",
			Handler:    _AssetsClient_QuoteSwapIn_Handler,
		},
		{
			MethodName: "ExecuteSwapIn",
			Handler:    _AssetsClient_ExecuteSwapIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clientassets.proto",
}
