// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: asset_deposits.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const addAssetDeposit = `-- name: AddAssetDeposit :exec
INSERT INTO asset_deposits (
    deposit_id,
    created_at,
    asset_id,
    amount,
    client_pubkey,
    server_pubkey,
    expiry,
    client_key_family,
    client_key_index,
    addr,
    protocol_version
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type AddAssetDepositParams struct {
	DepositID       string
	CreatedAt       time.Time
	AssetID         []byte
	Amount          int64
	ClientPubkey    []byte
	ServerPubkey    []byte
	Expiry          int32
	ClientKeyFamily int32
	ClientKeyIndex  int32
	Addr            string
	ProtocolVersion int32
}

func (q *Queries) AddAssetDeposit(ctx context.Context, arg AddAssetDepositParams) error {
	_, err := q.db.ExecContext(ctx, addAssetDeposit,
		arg.DepositID,
		arg.CreatedAt,
		arg.AssetID,
		arg.Amount,
		arg.ClientPubkey,
		arg.ServerPubkey,
		arg.Expiry,
		arg.ClientKeyFamily,
		arg.ClientKeyIndex,
		arg.Addr,
		arg.ProtocolVersion,
	)
	return err
}

const assetDeposiLeaseUTXO = `-- name: AssetDeposiLeaseUTXO :exec
INSERT INTO asset_deposit_leased_utxos (
    deposit_id, outpoint
) VALUES ($1, $2)
`

type AssetDeposiLeaseUTXOParams struct {
	DepositID string
	Outpoint  string
}

func (q *Queries) AssetDeposiLeaseUTXO(ctx context.Context, arg AssetDeposiLeaseUTXOParams) error {
	_, err := q.db.ExecContext(ctx, assetDeposiLeaseUTXO, arg.DepositID, arg.Outpoint)
	return err
}

const assetDepositReleaseUTXOs = `-- name: AssetDepositReleaseUTXOs :exec
DELETE FROM asset_deposit_leased_utxos
WHERE deposit_id = $1
`

func (q *Queries) AssetDepositReleaseUTXOs(ctx context.Context, depositID string) error {
	_, err := q.db.ExecContext(ctx, assetDepositReleaseUTXOs, depositID)
	return err
}

const getActiveAssetDeposits = `-- name: GetActiveAssetDeposits :many
SELECT d.deposit_id, d.created_at, d.asset_id, d.amount, d.client_pubkey, d.server_pubkey, d.expiry, d.client_key_family, d.client_key_index, d.addr, d.protocol_version, d.confirmation_height, d.outpoint, u.update_state, u.update_timestamp
FROM asset_deposits d
JOIN asset_deposit_updates u
  ON u.deposit_id = d.deposit_id
WHERE u.id = (
    SELECT id
    FROM asset_deposit_updates
    WHERE deposit_id = d.deposit_id
    ORDER BY update_timestamp DESC
    LIMIT 1
)
AND u.update_state IN (0, 1, 2, 3)
`

type GetActiveAssetDepositsRow struct {
	DepositID          string
	CreatedAt          time.Time
	AssetID            []byte
	Amount             int64
	ClientPubkey       []byte
	ServerPubkey       []byte
	Expiry             int32
	ClientKeyFamily    int32
	ClientKeyIndex     int32
	Addr               string
	ProtocolVersion    int32
	ConfirmationHeight sql.NullInt32
	Outpoint           sql.NullString
	UpdateState        int32
	UpdateTimestamp    time.Time
}

func (q *Queries) GetActiveAssetDeposits(ctx context.Context) ([]GetActiveAssetDepositsRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveAssetDeposits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveAssetDepositsRow
	for rows.Next() {
		var i GetActiveAssetDepositsRow
		if err := rows.Scan(
			&i.DepositID,
			&i.CreatedAt,
			&i.AssetID,
			&i.Amount,
			&i.ClientPubkey,
			&i.ServerPubkey,
			&i.Expiry,
			&i.ClientKeyFamily,
			&i.ClientKeyIndex,
			&i.Addr,
			&i.ProtocolVersion,
			&i.ConfirmationHeight,
			&i.Outpoint,
			&i.UpdateState,
			&i.UpdateTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssetDeposit = `-- name: GetAssetDeposit :one
SELECT d.deposit_id, d.created_at, d.asset_id, d.amount, d.client_pubkey, d.server_pubkey, d.expiry, d.client_key_family, d.client_key_index, d.addr, d.protocol_version, d.confirmation_height, d.outpoint, u.update_state, u.update_timestamp
FROM asset_deposits d
JOIN asset_deposit_updates u ON u.id = (
    SELECT id
    FROM asset_deposit_updates
    WHERE deposit_id = d.deposit_id
    ORDER BY update_timestamp DESC
    LIMIT 1
)
WHERE d.deposit_id = $1
`

type GetAssetDepositRow struct {
	DepositID          string
	CreatedAt          time.Time
	AssetID            []byte
	Amount             int64
	ClientPubkey       []byte
	ServerPubkey       []byte
	Expiry             int32
	ClientKeyFamily    int32
	ClientKeyIndex     int32
	Addr               string
	ProtocolVersion    int32
	ConfirmationHeight sql.NullInt32
	Outpoint           sql.NullString
	UpdateState        int32
	UpdateTimestamp    time.Time
}

func (q *Queries) GetAssetDeposit(ctx context.Context, depositID string) (GetAssetDepositRow, error) {
	row := q.db.QueryRowContext(ctx, getAssetDeposit, depositID)
	var i GetAssetDepositRow
	err := row.Scan(
		&i.DepositID,
		&i.CreatedAt,
		&i.AssetID,
		&i.Amount,
		&i.ClientPubkey,
		&i.ServerPubkey,
		&i.Expiry,
		&i.ClientKeyFamily,
		&i.ClientKeyIndex,
		&i.Addr,
		&i.ProtocolVersion,
		&i.ConfirmationHeight,
		&i.Outpoint,
		&i.UpdateState,
		&i.UpdateTimestamp,
	)
	return i, err
}

const getAssetDepositLeasedUTXOs = `-- name: GetAssetDepositLeasedUTXOs :many
SELECT deposit_id, outpoint FROM asset_deposit_leased_utxos
`

type GetAssetDepositLeasedUTXOsRow struct {
	DepositID string
	Outpoint  string
}

func (q *Queries) GetAssetDepositLeasedUTXOs(ctx context.Context) ([]GetAssetDepositLeasedUTXOsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAssetDepositLeasedUTXOs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAssetDepositLeasedUTXOsRow
	for rows.Next() {
		var i GetAssetDepositLeasedUTXOsRow
		if err := rows.Scan(&i.DepositID, &i.Outpoint); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssetDeposits = `-- name: GetAssetDeposits :many
SELECT d.deposit_id, d.created_at, d.asset_id, d.amount, d.client_pubkey, d.server_pubkey, d.expiry, d.client_key_family, d.client_key_index, d.addr, d.protocol_version, d.confirmation_height, d.outpoint, u.update_state, u.update_timestamp
FROM asset_deposits d
JOIN asset_deposit_updates u ON u.id = (
    SELECT id
    FROM asset_deposit_updates
    WHERE deposit_id = d.deposit_id
    ORDER BY update_timestamp DESC
    LIMIT 1
)
ORDER BY d.created_at ASC
`

type GetAssetDepositsRow struct {
	DepositID          string
	CreatedAt          time.Time
	AssetID            []byte
	Amount             int64
	ClientPubkey       []byte
	ServerPubkey       []byte
	Expiry             int32
	ClientKeyFamily    int32
	ClientKeyIndex     int32
	Addr               string
	ProtocolVersion    int32
	ConfirmationHeight sql.NullInt32
	Outpoint           sql.NullString
	UpdateState        int32
	UpdateTimestamp    time.Time
}

func (q *Queries) GetAssetDeposits(ctx context.Context) ([]GetAssetDepositsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAssetDeposits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAssetDepositsRow
	for rows.Next() {
		var i GetAssetDepositsRow
		if err := rows.Scan(
			&i.DepositID,
			&i.CreatedAt,
			&i.AssetID,
			&i.Amount,
			&i.ClientPubkey,
			&i.ServerPubkey,
			&i.Expiry,
			&i.ClientKeyFamily,
			&i.ClientKeyIndex,
			&i.Addr,
			&i.ProtocolVersion,
			&i.ConfirmationHeight,
			&i.Outpoint,
			&i.UpdateState,
			&i.UpdateTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDepositConfirmed = `-- name: MarkDepositConfirmed :exec
UPDATE asset_deposits 
SET confirmation_height = $2, outpoint = $3
WHERE deposit_id = $1
`

type MarkDepositConfirmedParams struct {
	DepositID          string
	ConfirmationHeight sql.NullInt32
	Outpoint           sql.NullString
}

func (q *Queries) MarkDepositConfirmed(ctx context.Context, arg MarkDepositConfirmedParams) error {
	_, err := q.db.ExecContext(ctx, markDepositConfirmed, arg.DepositID, arg.ConfirmationHeight, arg.Outpoint)
	return err
}

const updateDepositState = `-- name: UpdateDepositState :exec
INSERT INTO asset_deposit_updates (
    deposit_id,
    update_state,
    update_timestamp
) VALUES ($1, $2, $3)
`

type UpdateDepositStateParams struct {
	DepositID       string
	UpdateState     int32
	UpdateTimestamp time.Time
}

func (q *Queries) UpdateDepositState(ctx context.Context, arg UpdateDepositStateParams) error {
	_, err := q.db.ExecContext(ctx, updateDepositState, arg.DepositID, arg.UpdateState, arg.UpdateTimestamp)
	return err
}
