// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package swapserverrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AssetDepositServiceClient is the client API for AssetDepositService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssetDepositServiceClient interface {
	// NewAssetDeposit creates a new asset deposit address.
	NewAssetDeposit(ctx context.Context, in *NewAssetDepositRequest, opts ...grpc.CallOption) (*NewAssetDepositResponse, error)
}

type assetDepositServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetDepositServiceClient(cc grpc.ClientConnInterface) AssetDepositServiceClient {
	return &assetDepositServiceClient{cc}
}

func (c *assetDepositServiceClient) NewAssetDeposit(ctx context.Context, in *NewAssetDepositRequest, opts ...grpc.CallOption) (*NewAssetDepositResponse, error) {
	out := new(NewAssetDepositResponse)
	err := c.cc.Invoke(ctx, "/looprpc.AssetDepositService/NewAssetDeposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetDepositServiceServer is the server API for AssetDepositService service.
// All implementations must embed UnimplementedAssetDepositServiceServer
// for forward compatibility
type AssetDepositServiceServer interface {
	// NewAssetDeposit creates a new asset deposit address.
	NewAssetDeposit(context.Context, *NewAssetDepositRequest) (*NewAssetDepositResponse, error)
	mustEmbedUnimplementedAssetDepositServiceServer()
}

// UnimplementedAssetDepositServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAssetDepositServiceServer struct {
}

func (UnimplementedAssetDepositServiceServer) NewAssetDeposit(context.Context, *NewAssetDepositRequest) (*NewAssetDepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewAssetDeposit not implemented")
}
func (UnimplementedAssetDepositServiceServer) mustEmbedUnimplementedAssetDepositServiceServer() {}

// UnsafeAssetDepositServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetDepositServiceServer will
// result in compilation errors.
type UnsafeAssetDepositServiceServer interface {
	mustEmbedUnimplementedAssetDepositServiceServer()
}

func RegisterAssetDepositServiceServer(s grpc.ServiceRegistrar, srv AssetDepositServiceServer) {
	s.RegisterService(&AssetDepositService_ServiceDesc, srv)
}

func _AssetDepositService_NewAssetDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewAssetDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetDepositServiceServer).NewAssetDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/looprpc.AssetDepositService/NewAssetDeposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetDepositServiceServer).NewAssetDeposit(ctx, req.(*NewAssetDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetDepositService_ServiceDesc is the grpc.ServiceDesc for AssetDepositService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetDepositService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "looprpc.AssetDepositService",
	HandlerType: (*AssetDepositServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewAssetDeposit",
			Handler:    _AssetDepositService_NewAssetDeposit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "asset_deposit.proto",
}
