// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: asset_deposit.proto

// We can't change this to swapserverrpc, it would be a breaking change because
// the package name is also contained in the HTTP URIs and old clients would
// call the wrong endpoints. Luckily with the go_package option we can have
// different golang and RPC package names to fix protobuf namespace conflicts.

package swapserverrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AssetDepositProtocolVersion is the version of the asset deposit protocol.
type AssetDepositProtocolVersion int32

const (
	// V0 is the first version of the asset deposit protocol.
	AssetDepositProtocolVersion_ASSET_DEPOSIT_V0 AssetDepositProtocolVersion = 0
)

// Enum value maps for AssetDepositProtocolVersion.
var (
	AssetDepositProtocolVersion_name = map[int32]string{
		0: "ASSET_DEPOSIT_V0",
	}
	AssetDepositProtocolVersion_value = map[string]int32{
		"ASSET_DEPOSIT_V0": 0,
	}
)

func (x AssetDepositProtocolVersion) Enum() *AssetDepositProtocolVersion {
	p := new(AssetDepositProtocolVersion)
	*p = x
	return p
}

func (x AssetDepositProtocolVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetDepositProtocolVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_asset_deposit_proto_enumTypes[0].Descriptor()
}

func (AssetDepositProtocolVersion) Type() protoreflect.EnumType {
	return &file_asset_deposit_proto_enumTypes[0]
}

func (x AssetDepositProtocolVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetDepositProtocolVersion.Descriptor instead.
func (AssetDepositProtocolVersion) EnumDescriptor() ([]byte, []int) {
	return file_asset_deposit_proto_rawDescGZIP(), []int{0}
}

// NewAssetDepositServerReq is the request to the Server to create a new asset
// deposit.
type NewAssetDepositServerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// asset_id is the id of the asset to deposit.
	AssetId []byte `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// amount is the amount of the asset to deposit.
	Amount uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// client_key is the public key of the client.
	ClientKey []byte `protobuf:"bytes,3,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`
	// csv_expiry is the CSV expiry for the deposit transaction.
	CsvExpiry int32 `protobuf:"varint,4,opt,name=csv_expiry,json=csvExpiry,proto3" json:"csv_expiry,omitempty"`
}

func (x *NewAssetDepositServerReq) Reset() {
	*x = NewAssetDepositServerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asset_deposit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewAssetDepositServerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAssetDepositServerReq) ProtoMessage() {}

func (x *NewAssetDepositServerReq) ProtoReflect() protoreflect.Message {
	mi := &file_asset_deposit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAssetDepositServerReq.ProtoReflect.Descriptor instead.
func (*NewAssetDepositServerReq) Descriptor() ([]byte, []int) {
	return file_asset_deposit_proto_rawDescGZIP(), []int{0}
}

func (x *NewAssetDepositServerReq) GetAssetId() []byte {
	if x != nil {
		return x.AssetId
	}
	return nil
}

func (x *NewAssetDepositServerReq) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *NewAssetDepositServerReq) GetClientKey() []byte {
	if x != nil {
		return x.ClientKey
	}
	return nil
}

func (x *NewAssetDepositServerReq) GetCsvExpiry() int32 {
	if x != nil {
		return x.CsvExpiry
	}
	return 0
}

// NewAssetDepositServerRes is the Server's response to a NewAssetDeposit
// request.
type NewAssetDepositServerRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// deposit_id is the unique id of the deposit.
	DepositId string `protobuf:"bytes,1,opt,name=deposit_id,json=depositId,proto3" json:"deposit_id,omitempty"`
	// server_key is the public key of the server.
	ServerKey []byte `protobuf:"bytes,2,opt,name=server_key,json=serverKey,proto3" json:"server_key,omitempty"`
	// deposit_addr is the TAP address to deposit the asset to.
	DepositAddr string `protobuf:"bytes,3,opt,name=deposit_addr,json=depositAddr,proto3" json:"deposit_addr,omitempty"`
}

func (x *NewAssetDepositServerRes) Reset() {
	*x = NewAssetDepositServerRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asset_deposit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewAssetDepositServerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAssetDepositServerRes) ProtoMessage() {}

func (x *NewAssetDepositServerRes) ProtoReflect() protoreflect.Message {
	mi := &file_asset_deposit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAssetDepositServerRes.ProtoReflect.Descriptor instead.
func (*NewAssetDepositServerRes) Descriptor() ([]byte, []int) {
	return file_asset_deposit_proto_rawDescGZIP(), []int{1}
}

func (x *NewAssetDepositServerRes) GetDepositId() string {
	if x != nil {
		return x.DepositId
	}
	return ""
}

func (x *NewAssetDepositServerRes) GetServerKey() []byte {
	if x != nil {
		return x.ServerKey
	}
	return nil
}

func (x *NewAssetDepositServerRes) GetDepositAddr() string {
	if x != nil {
		return x.DepositAddr
	}
	return ""
}

// TODO(bhandras): support spending multiple deposits into a single htlc.
type CoSignHtlcReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// deposit_id is the id of the deposit.
	DepositId  string `protobuf:"bytes,1,opt,name=deposit_id,json=depositId,proto3" json:"deposit_id,omitempty"`
	Psbt       []byte `protobuf:"bytes,2,opt,name=psbt,proto3" json:"psbt,omitempty"`
	Nonce      []byte `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	PartialSig []byte `protobuf:"bytes,4,opt,name=partial_sig,json=partialSig,proto3" json:"partial_sig,omitempty"`
}

func (x *CoSignHtlcReq) Reset() {
	*x = CoSignHtlcReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asset_deposit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoSignHtlcReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoSignHtlcReq) ProtoMessage() {}

func (x *CoSignHtlcReq) ProtoReflect() protoreflect.Message {
	mi := &file_asset_deposit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoSignHtlcReq.ProtoReflect.Descriptor instead.
func (*CoSignHtlcReq) Descriptor() ([]byte, []int) {
	return file_asset_deposit_proto_rawDescGZIP(), []int{2}
}

func (x *CoSignHtlcReq) GetDepositId() string {
	if x != nil {
		return x.DepositId
	}
	return ""
}

func (x *CoSignHtlcReq) GetPsbt() []byte {
	if x != nil {
		return x.Psbt
	}
	return nil
}

func (x *CoSignHtlcReq) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *CoSignHtlcReq) GetPartialSig() []byte {
	if x != nil {
		return x.PartialSig
	}
	return nil
}

type CoSignHtlcRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CoSignHtlcRes) Reset() {
	*x = CoSignHtlcRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asset_deposit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoSignHtlcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoSignHtlcRes) ProtoMessage() {}

func (x *CoSignHtlcRes) ProtoReflect() protoreflect.Message {
	mi := &file_asset_deposit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoSignHtlcRes.ProtoReflect.Descriptor instead.
func (*CoSignHtlcRes) Descriptor() ([]byte, []int) {
	return file_asset_deposit_proto_rawDescGZIP(), []int{3}
}

var File_asset_deposit_proto protoreflect.FileDescriptor

var file_asset_deposit_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6c, 0x6f, 0x6f, 0x70, 0x72, 0x70, 0x63, 0x22, 0x8b,
	0x01, 0x0a, 0x18, 0x4e, 0x65, 0x77, 0x41, 0x73, 0x73, 0x65, 0x74, 0x44, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x73, 0x76, 0x5f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x63, 0x73, 0x76, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79, 0x22, 0x7b, 0x0a, 0x18,
	0x4e, 0x65, 0x77, 0x41, 0x73, 0x73, 0x65, 0x74, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x64, 0x64, 0x72, 0x22, 0x79, 0x0a, 0x0d, 0x43, 0x6f, 0x53,
	0x69, 0x67, 0x6e, 0x48, 0x74, 0x6c, 0x63, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x73, 0x62,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x70, 0x73, 0x62, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6e, 0x6f,
	0x6e, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x73,
	0x69, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61,
	0x6c, 0x53, 0x69, 0x67, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x6f, 0x53, 0x69, 0x67, 0x6e, 0x48, 0x74,
	0x6c, 0x63, 0x52, 0x65, 0x73, 0x2a, 0x33, 0x0a, 0x1b, 0x41, 0x73, 0x73, 0x65, 0x74, 0x44, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x10, 0x41, 0x53, 0x53, 0x45, 0x54, 0x5f, 0x44, 0x45,
	0x50, 0x4f, 0x53, 0x49, 0x54, 0x5f, 0x56, 0x30, 0x10, 0x00, 0x32, 0xac, 0x01, 0x0a, 0x13, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x57, 0x0a, 0x0f, 0x4e, 0x65, 0x77, 0x41, 0x73, 0x73, 0x65, 0x74, 0x44, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x12, 0x21, 0x2e, 0x6c, 0x6f, 0x6f, 0x70, 0x72, 0x70, 0x63, 0x2e,
	0x4e, 0x65, 0x77, 0x41, 0x73, 0x73, 0x65, 0x74, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x6c, 0x6f, 0x6f, 0x70, 0x72,
	0x70, 0x63, 0x2e, 0x4e, 0x65, 0x77, 0x41, 0x73, 0x73, 0x65, 0x74, 0x44, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x0a, 0x43,
	0x6f, 0x53, 0x69, 0x67, 0x6e, 0x48, 0x74, 0x6c, 0x63, 0x12, 0x16, 0x2e, 0x6c, 0x6f, 0x6f, 0x70,
	0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x53, 0x69, 0x67, 0x6e, 0x48, 0x74, 0x6c, 0x63, 0x52, 0x65,
	0x71, 0x1a, 0x16, 0x2e, 0x6c, 0x6f, 0x6f, 0x70, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x53, 0x69,
	0x67, 0x6e, 0x48, 0x74, 0x6c, 0x63, 0x52, 0x65, 0x73, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x69, 0x6e,
	0x67, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x6c, 0x6f, 0x6f, 0x70, 0x2f, 0x73, 0x77, 0x61, 0x70, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_asset_deposit_proto_rawDescOnce sync.Once
	file_asset_deposit_proto_rawDescData = file_asset_deposit_proto_rawDesc
)

func file_asset_deposit_proto_rawDescGZIP() []byte {
	file_asset_deposit_proto_rawDescOnce.Do(func() {
		file_asset_deposit_proto_rawDescData = protoimpl.X.CompressGZIP(file_asset_deposit_proto_rawDescData)
	})
	return file_asset_deposit_proto_rawDescData
}

var file_asset_deposit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_asset_deposit_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_asset_deposit_proto_goTypes = []any{
	(AssetDepositProtocolVersion)(0), // 0: looprpc.AssetDepositProtocolVersion
	(*NewAssetDepositServerReq)(nil), // 1: looprpc.NewAssetDepositServerReq
	(*NewAssetDepositServerRes)(nil), // 2: looprpc.NewAssetDepositServerRes
	(*CoSignHtlcReq)(nil),            // 3: looprpc.CoSignHtlcReq
	(*CoSignHtlcRes)(nil),            // 4: looprpc.CoSignHtlcRes
}
var file_asset_deposit_proto_depIdxs = []int32{
	1, // 0: looprpc.AssetDepositService.NewAssetDeposit:input_type -> looprpc.NewAssetDepositServerReq
	3, // 1: looprpc.AssetDepositService.CoSignHtlc:input_type -> looprpc.CoSignHtlcReq
	2, // 2: looprpc.AssetDepositService.NewAssetDeposit:output_type -> looprpc.NewAssetDepositServerRes
	4, // 3: looprpc.AssetDepositService.CoSignHtlc:output_type -> looprpc.CoSignHtlcRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_asset_deposit_proto_init() }
func file_asset_deposit_proto_init() {
	if File_asset_deposit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_asset_deposit_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*NewAssetDepositServerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asset_deposit_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*NewAssetDepositServerRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asset_deposit_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CoSignHtlcReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asset_deposit_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CoSignHtlcRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_asset_deposit_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asset_deposit_proto_goTypes,
		DependencyIndexes: file_asset_deposit_proto_depIdxs,
		EnumInfos:         file_asset_deposit_proto_enumTypes,
		MessageInfos:      file_asset_deposit_proto_msgTypes,
	}.Build()
	File_asset_deposit_proto = out.File
	file_asset_deposit_proto_rawDesc = nil
	file_asset_deposit_proto_goTypes = nil
	file_asset_deposit_proto_depIdxs = nil
}
