// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package swapserverrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AssetsSwapServerClient is the client API for AssetsSwapServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssetsSwapServerClient interface {
	// QuoteAssetLoopOut requests a quote for an asset loop out swap from the
	// server.
	QuoteAssetLoopOut(ctx context.Context, in *QuoteAssetLoopOutRequest, opts ...grpc.CallOption) (*QuoteAssetLoopOutResponse, error)
	// ListAvailableAssets returns the list of assets that the server supports.
	ListAvailableAssets(ctx context.Context, in *ListAvailableAssetsRequest, opts ...grpc.CallOption) (*ListAvailableAssetsResponse, error)
	// RequestAssetLoopOut requests an asset loop out swap from the server.
	RequestAssetLoopOut(ctx context.Context, in *RequestAssetLoopOutRequest, opts ...grpc.CallOption) (*RequestAssetLoopOutResponse, error)
	// PollAssetLoopOutProof requests the server to poll for the proof of the
	// asset loop out swap.
	PollAssetLoopOutProof(ctx context.Context, in *PollAssetLoopOutProofRequest, opts ...grpc.CallOption) (*PollAssetLoopOutProofResponse, error)
	// RequestAssetBuy requests an asset buy swap from the server. This
	// requires an already confirmed asset output on chain.
	RequestAssetBuy(ctx context.Context, in *RequestAssetBuyRequest, opts ...grpc.CallOption) (*RequestAssetBuyResponse, error)
	// RequestMusig2Sweep requests a musig2 sweep from the server.
	RequestMusig2Sweep(ctx context.Context, in *RequestMusig2SweepRequest, opts ...grpc.CallOption) (*RequestMusig2SweepResponse, error)
	// NewAssetLoopIn requests a new asset loop in swap from the server.
	NewAssetLoopIn(ctx context.Context, in *NewAssetLoopInRequest, opts ...grpc.CallOption) (*NewAssetLoopInResponse, error)
	// QuoteAssetLoopIn returns a quote for an initiated asset loopin swap.
	QuoteAssetLoopIn(ctx context.Context, in *QuoteAssetLoopInRequest, opts ...grpc.CallOption) (*QuoteAssetLoopInResponse, error)
	// ExecuteAssetLoopIn executes an initiated asset loopin swap.
	ExecuteAssetLoopIn(ctx context.Context, in *ExecuteAssetLoopInRequest, opts ...grpc.CallOption) (*ExecuteAssetLoopInResponse, error)
	RevealOutputProof(ctx context.Context, in *RevealOutputProofRequest, opts ...grpc.CallOption) (*RevealOutputProofResponse, error)
}

type assetsSwapServerClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetsSwapServerClient(cc grpc.ClientConnInterface) AssetsSwapServerClient {
	return &assetsSwapServerClient{cc}
}

func (c *assetsSwapServerClient) QuoteAssetLoopOut(ctx context.Context, in *QuoteAssetLoopOutRequest, opts ...grpc.CallOption) (*QuoteAssetLoopOutResponse, error) {
	out := new(QuoteAssetLoopOutResponse)
	err := c.cc.Invoke(ctx, "/looprpc.AssetsSwapServer/QuoteAssetLoopOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsSwapServerClient) ListAvailableAssets(ctx context.Context, in *ListAvailableAssetsRequest, opts ...grpc.CallOption) (*ListAvailableAssetsResponse, error) {
	out := new(ListAvailableAssetsResponse)
	err := c.cc.Invoke(ctx, "/looprpc.AssetsSwapServer/ListAvailableAssets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsSwapServerClient) RequestAssetLoopOut(ctx context.Context, in *RequestAssetLoopOutRequest, opts ...grpc.CallOption) (*RequestAssetLoopOutResponse, error) {
	out := new(RequestAssetLoopOutResponse)
	err := c.cc.Invoke(ctx, "/looprpc.AssetsSwapServer/RequestAssetLoopOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsSwapServerClient) PollAssetLoopOutProof(ctx context.Context, in *PollAssetLoopOutProofRequest, opts ...grpc.CallOption) (*PollAssetLoopOutProofResponse, error) {
	out := new(PollAssetLoopOutProofResponse)
	err := c.cc.Invoke(ctx, "/looprpc.AssetsSwapServer/PollAssetLoopOutProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsSwapServerClient) RequestAssetBuy(ctx context.Context, in *RequestAssetBuyRequest, opts ...grpc.CallOption) (*RequestAssetBuyResponse, error) {
	out := new(RequestAssetBuyResponse)
	err := c.cc.Invoke(ctx, "/looprpc.AssetsSwapServer/RequestAssetBuy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsSwapServerClient) RequestMusig2Sweep(ctx context.Context, in *RequestMusig2SweepRequest, opts ...grpc.CallOption) (*RequestMusig2SweepResponse, error) {
	out := new(RequestMusig2SweepResponse)
	err := c.cc.Invoke(ctx, "/looprpc.AssetsSwapServer/RequestMusig2Sweep", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsSwapServerClient) NewAssetLoopIn(ctx context.Context, in *NewAssetLoopInRequest, opts ...grpc.CallOption) (*NewAssetLoopInResponse, error) {
	out := new(NewAssetLoopInResponse)
	err := c.cc.Invoke(ctx, "/looprpc.AssetsSwapServer/NewAssetLoopIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsSwapServerClient) QuoteAssetLoopIn(ctx context.Context, in *QuoteAssetLoopInRequest, opts ...grpc.CallOption) (*QuoteAssetLoopInResponse, error) {
	out := new(QuoteAssetLoopInResponse)
	err := c.cc.Invoke(ctx, "/looprpc.AssetsSwapServer/QuoteAssetLoopIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsSwapServerClient) ExecuteAssetLoopIn(ctx context.Context, in *ExecuteAssetLoopInRequest, opts ...grpc.CallOption) (*ExecuteAssetLoopInResponse, error) {
	out := new(ExecuteAssetLoopInResponse)
	err := c.cc.Invoke(ctx, "/looprpc.AssetsSwapServer/ExecuteAssetLoopIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsSwapServerClient) RevealOutputProof(ctx context.Context, in *RevealOutputProofRequest, opts ...grpc.CallOption) (*RevealOutputProofResponse, error) {
	out := new(RevealOutputProofResponse)
	err := c.cc.Invoke(ctx, "/looprpc.AssetsSwapServer/RevealOutputProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetsSwapServerServer is the server API for AssetsSwapServer service.
// All implementations must embed UnimplementedAssetsSwapServerServer
// for forward compatibility
type AssetsSwapServerServer interface {
	// QuoteAssetLoopOut requests a quote for an asset loop out swap from the
	// server.
	QuoteAssetLoopOut(context.Context, *QuoteAssetLoopOutRequest) (*QuoteAssetLoopOutResponse, error)
	// ListAvailableAssets returns the list of assets that the server supports.
	ListAvailableAssets(context.Context, *ListAvailableAssetsRequest) (*ListAvailableAssetsResponse, error)
	// RequestAssetLoopOut requests an asset loop out swap from the server.
	RequestAssetLoopOut(context.Context, *RequestAssetLoopOutRequest) (*RequestAssetLoopOutResponse, error)
	// PollAssetLoopOutProof requests the server to poll for the proof of the
	// asset loop out swap.
	PollAssetLoopOutProof(context.Context, *PollAssetLoopOutProofRequest) (*PollAssetLoopOutProofResponse, error)
	// RequestAssetBuy requests an asset buy swap from the server. This
	// requires an already confirmed asset output on chain.
	RequestAssetBuy(context.Context, *RequestAssetBuyRequest) (*RequestAssetBuyResponse, error)
	// RequestMusig2Sweep requests a musig2 sweep from the server.
	RequestMusig2Sweep(context.Context, *RequestMusig2SweepRequest) (*RequestMusig2SweepResponse, error)
	// NewAssetLoopIn requests a new asset loop in swap from the server.
	NewAssetLoopIn(context.Context, *NewAssetLoopInRequest) (*NewAssetLoopInResponse, error)
	// QuoteAssetLoopIn returns a quote for an initiated asset loopin swap.
	QuoteAssetLoopIn(context.Context, *QuoteAssetLoopInRequest) (*QuoteAssetLoopInResponse, error)
	// ExecuteAssetLoopIn executes an initiated asset loopin swap.
	ExecuteAssetLoopIn(context.Context, *ExecuteAssetLoopInRequest) (*ExecuteAssetLoopInResponse, error)
	RevealOutputProof(context.Context, *RevealOutputProofRequest) (*RevealOutputProofResponse, error)
	mustEmbedUnimplementedAssetsSwapServerServer()
}

// UnimplementedAssetsSwapServerServer must be embedded to have forward compatible implementations.
type UnimplementedAssetsSwapServerServer struct {
}

func (UnimplementedAssetsSwapServerServer) QuoteAssetLoopOut(context.Context, *QuoteAssetLoopOutRequest) (*QuoteAssetLoopOutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuoteAssetLoopOut not implemented")
}
func (UnimplementedAssetsSwapServerServer) ListAvailableAssets(context.Context, *ListAvailableAssetsRequest) (*ListAvailableAssetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAvailableAssets not implemented")
}
func (UnimplementedAssetsSwapServerServer) RequestAssetLoopOut(context.Context, *RequestAssetLoopOutRequest) (*RequestAssetLoopOutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestAssetLoopOut not implemented")
}
func (UnimplementedAssetsSwapServerServer) PollAssetLoopOutProof(context.Context, *PollAssetLoopOutProofRequest) (*PollAssetLoopOutProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PollAssetLoopOutProof not implemented")
}
func (UnimplementedAssetsSwapServerServer) RequestAssetBuy(context.Context, *RequestAssetBuyRequest) (*RequestAssetBuyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestAssetBuy not implemented")
}
func (UnimplementedAssetsSwapServerServer) RequestMusig2Sweep(context.Context, *RequestMusig2SweepRequest) (*RequestMusig2SweepResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestMusig2Sweep not implemented")
}
func (UnimplementedAssetsSwapServerServer) NewAssetLoopIn(context.Context, *NewAssetLoopInRequest) (*NewAssetLoopInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewAssetLoopIn not implemented")
}
func (UnimplementedAssetsSwapServerServer) QuoteAssetLoopIn(context.Context, *QuoteAssetLoopInRequest) (*QuoteAssetLoopInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuoteAssetLoopIn not implemented")
}
func (UnimplementedAssetsSwapServerServer) ExecuteAssetLoopIn(context.Context, *ExecuteAssetLoopInRequest) (*ExecuteAssetLoopInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteAssetLoopIn not implemented")
}
func (UnimplementedAssetsSwapServerServer) RevealOutputProof(context.Context, *RevealOutputProofRequest) (*RevealOutputProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevealOutputProof not implemented")
}
func (UnimplementedAssetsSwapServerServer) mustEmbedUnimplementedAssetsSwapServerServer() {}

// UnsafeAssetsSwapServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetsSwapServerServer will
// result in compilation errors.
type UnsafeAssetsSwapServerServer interface {
	mustEmbedUnimplementedAssetsSwapServerServer()
}

func RegisterAssetsSwapServerServer(s grpc.ServiceRegistrar, srv AssetsSwapServerServer) {
	s.RegisterService(&AssetsSwapServer_ServiceDesc, srv)
}

func _AssetsSwapServer_QuoteAssetLoopOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteAssetLoopOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsSwapServerServer).QuoteAssetLoopOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/looprpc.AssetsSwapServer/QuoteAssetLoopOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsSwapServerServer).QuoteAssetLoopOut(ctx, req.(*QuoteAssetLoopOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsSwapServer_ListAvailableAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAvailableAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsSwapServerServer).ListAvailableAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/looprpc.AssetsSwapServer/ListAvailableAssets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsSwapServerServer).ListAvailableAssets(ctx, req.(*ListAvailableAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsSwapServer_RequestAssetLoopOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAssetLoopOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsSwapServerServer).RequestAssetLoopOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/looprpc.AssetsSwapServer/RequestAssetLoopOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsSwapServerServer).RequestAssetLoopOut(ctx, req.(*RequestAssetLoopOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsSwapServer_PollAssetLoopOutProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollAssetLoopOutProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsSwapServerServer).PollAssetLoopOutProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/looprpc.AssetsSwapServer/PollAssetLoopOutProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsSwapServerServer).PollAssetLoopOutProof(ctx, req.(*PollAssetLoopOutProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsSwapServer_RequestAssetBuy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAssetBuyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsSwapServerServer).RequestAssetBuy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/looprpc.AssetsSwapServer/RequestAssetBuy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsSwapServerServer).RequestAssetBuy(ctx, req.(*RequestAssetBuyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsSwapServer_RequestMusig2Sweep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMusig2SweepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsSwapServerServer).RequestMusig2Sweep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/looprpc.AssetsSwapServer/RequestMusig2Sweep",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsSwapServerServer).RequestMusig2Sweep(ctx, req.(*RequestMusig2SweepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsSwapServer_NewAssetLoopIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewAssetLoopInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsSwapServerServer).NewAssetLoopIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/looprpc.AssetsSwapServer/NewAssetLoopIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsSwapServerServer).NewAssetLoopIn(ctx, req.(*NewAssetLoopInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsSwapServer_QuoteAssetLoopIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteAssetLoopInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsSwapServerServer).QuoteAssetLoopIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/looprpc.AssetsSwapServer/QuoteAssetLoopIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsSwapServerServer).QuoteAssetLoopIn(ctx, req.(*QuoteAssetLoopInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsSwapServer_ExecuteAssetLoopIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteAssetLoopInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsSwapServerServer).ExecuteAssetLoopIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/looprpc.AssetsSwapServer/ExecuteAssetLoopIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsSwapServerServer).ExecuteAssetLoopIn(ctx, req.(*ExecuteAssetLoopInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsSwapServer_RevealOutputProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevealOutputProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsSwapServerServer).RevealOutputProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/looprpc.AssetsSwapServer/RevealOutputProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsSwapServerServer).RevealOutputProof(ctx, req.(*RevealOutputProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetsSwapServer_ServiceDesc is the grpc.ServiceDesc for AssetsSwapServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetsSwapServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "looprpc.AssetsSwapServer",
	HandlerType: (*AssetsSwapServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QuoteAssetLoopOut",
			Handler:    _AssetsSwapServer_QuoteAssetLoopOut_Handler,
		},
		{
			MethodName: "ListAvailableAssets",
			Handler:    _AssetsSwapServer_ListAvailableAssets_Handler,
		},
		{
			MethodName: "RequestAssetLoopOut",
			Handler:    _AssetsSwapServer_RequestAssetLoopOut_Handler,
		},
		{
			MethodName: "PollAssetLoopOutProof",
			Handler:    _AssetsSwapServer_PollAssetLoopOutProof_Handler,
		},
		{
			MethodName: "RequestAssetBuy",
			Handler:    _AssetsSwapServer_RequestAssetBuy_Handler,
		},
		{
			MethodName: "RequestMusig2Sweep",
			Handler:    _AssetsSwapServer_RequestMusig2Sweep_Handler,
		},
		{
			MethodName: "NewAssetLoopIn",
			Handler:    _AssetsSwapServer_NewAssetLoopIn_Handler,
		},
		{
			MethodName: "QuoteAssetLoopIn",
			Handler:    _AssetsSwapServer_QuoteAssetLoopIn_Handler,
		},
		{
			MethodName: "ExecuteAssetLoopIn",
			Handler:    _AssetsSwapServer_ExecuteAssetLoopIn_Handler,
		},
		{
			MethodName: "RevealOutputProof",
			Handler:    _AssetsSwapServer_RevealOutputProof_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assets.proto",
}
